// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Uf95hxcEhCy3w9PofQXGlD1dfHIaOqg',
    appId: '1:212211182118:web:ab8b66dce3dbd7c1a314e7',
    messagingSenderId: '212211182118',
    projectId: 'shuraksha-902ce',
    authDomain: 'shuraksha-902ce.firebaseapp.com',
    storageBucket: 'shuraksha-902ce.appspot.com',
    measurementId: 'G-F423FVVV3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkD5c1fW8No8k-FDH4iWKxt7GW80TR8Co',
    appId: '1:212211182118:android:991de24c5af3eb02a314e7',
    messagingSenderId: '212211182118',
    projectId: 'shuraksha-902ce',
    storageBucket: 'shuraksha-902ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcW5XSDz1X2sH8Yl7ZJ6NsUHSdUM-NKqA',
    appId: '1:212211182118:ios:83887fa47f6d8347a314e7',
    messagingSenderId: '212211182118',
    projectId: 'shuraksha-902ce',
    storageBucket: 'shuraksha-902ce.appspot.com',
    iosClientId: '212211182118-ne6h2ocjjpejo9mdmftbpm69e1ed3fm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shuraksha1',
  );
}
